/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        "secondary-blue-50": "#e6e6f2",
        "secondary-blue-100": "#b3b3d5",
        "secondary-blue-200": "#8e8ec1",
        "secondary-blue-300": "#5a5aa5",
        "secondary-blue-400": "#3a3a94",
        "secondary-blue-500": "#090979",
        "secondary-blue-600": "#08086e",
        "secondary-blue-700": "#060656",
        "secondary-blue-800": "#050543",
        "secondary-blue-900": "#040433",
        "secondary-purple-50": "#f8f7ff",
        "secondary-purple-100": "#e8e7ff",
        "secondary-purple-200": "#dddcff",
        "secondary-purple-300": "#cecbff",
        "secondary-purple-400": "#c5c1ff",
        "secondary-purple-500": "#b6b2ff",
        "secondary-purple-600": "#a6a2e8",
        "secondary-purple-700": "#817eb5",
        "secondary-purple-800": "#64628c",
        "secondary-purple-900": "#4c4b6b",
        "primary-blue-50": "#e6f7ff",
        "primary-blue-100": "#b0e5ff",
        "primary-blue-200": "#8ad8ff",
        "primary-blue-300": "#54c6ff",
        "primary-blue-400": "#33bbff",
        "primary-blue": "#00aaff",
        "primary-blue-600": "#009be8",
        "primary-blue-700": "#0079b5",
        "primary-blue-800": "#005e8c",
        "primary-blue-900": "#00476b",
        "primary-purple-50": "#f1e6ff",
        "primary-purple-100": "#d3b0ff",
        "primary-purple-200": "#bd8aff",
        "primary-purple-300": "#9f54ff",
        "primary-purple-400": "#8d33ff",
        "primary-purple-500": "#7000ff",
        "primary-purple-600": "#6600e8",
        "primary-purple-700": "#5000b5",
        "primary-purple-800": "#3e008c",
        "primary-purple-900": "#2f006b",
        "basic-1": "#ffffff",
        "basic-2": "#fcfcfd",
        "basic-3": "#f5f5f6",
        "basic-4": "#f0f0f1",
        "basic-5": "#d9d9dc",
        "basic-6": "#c0bfc4",
        "basic-7": "#8d8c95",
        "basic-8": "#5b5966",
        "basic-9": "#464553",
        "basic-10": "#282637",
        "basic-11": "#201f30",
        "basic-12": "#161427",
        "basic-13": "#020014",
        "brand-secondaryPurple": "#b5b2ff",
        "brand-secondaryBlue": "#090979",
        "brand-primaryBlue": "#00aaff",
        "brand-primaryPurple": "#7000ff",
        "brand-dark": "#020024",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
